apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-lovestory-build
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/dubba-anusha/lovestory-app.git"
            - "--dockerfile=Dockerfile"
            - "--destination=docker.io/anushadubba/lovestory-app:v1"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: dockerhub-secret
            items:
              - key: .dockerconfigjson
                path: config.json
